[package]
name = "tmptestpgci"
version = "0.1.4"
edition = "2024"

[dependencies]
color-eyre = "0.6.3"
sqlx = { version = "0.8.3", features = ["postgres", "runtime-tokio"] }
tokio = { version = "1.43.0", features = ["full"] }
